let places = [
  // Adding more places globally
  "Kabul",
  "Tashkent",
  "Dushanbe",
  "Bishkek",
  "Ashgabat",
  "Ulaanbaatar",
  "Yerevan",
  "Baku",
  "Chisinau",
  "Podgorica",
  "Ljubljana",
  "Zagreb",
  "Sarajevo",
  "Skopje",
  "Pristina",
  "Belgrade",
  "Sofia",
  "Bucharest",
  "Vilnius",
  "Riga",
  "Tallinn",
  "Bratislava",
  "Luxembourg City",
  "Vaduz",
  "Reykjavik",
  "Valletta",
  "Andorra la Vella",
  "San Marino",
  "Monaco",
  "Vatican City",
  "Port Moresby",
  "Honiara",
  "Suva",
  "Nuku'alofa",
  "Apia",
  "Majuro",
  "Funafuti",
  "Tarawa",
  "Yaren",
  "Noumea",
  "Papeete",
  "Port Vila",
  "Palikir",
  "Pago Pago",
  "Managua",
  "Belmopan",
  "Kingston",
  "Port-au-Prince",
  "Havana",
  "Basseterre",
  "Roseau",
  "Saint John's",
  "Castries",
  "Bridgetown",
  "Kingstown",
  "Port of Spain",
  "Georgetown",
  "Paramaribo",
  "Montevideo",
  "Asuncion",
  "La Paz",
  "Sucre",
  "Lima",
  "Quito",
  "Caracas",
  "Bogota",
  "San Salvador",
  "San Jose",
  "Tegucigalpa",
  "Guatemala City",
  "Manila",
  "Kuala Lumpur",
  "Singapore",
  "Jakarta",
  "Bangkok",
  "Hanoi",
  "Phnom Penh",
  "Vientiane",
  "Rangoon",
  "Naypyidaw",
  "Ulaanbaatar",
  "Thimphu",
  "Malé",
  "Colombo",
  "Kathmandu",
  "Pyongyang",
  "Seoul",
  "Taipei",
  "Hong Kong",
  "Macau",
  "Shanghai",
  "Guangzhou",
  "Chengdu",
  "Shenzhen",
  "Wuhan",
  "Hangzhou",
  "Nanjing",
  "Harbin",
  "Shenyang",
  "Changsha",
  "Kunming",
  "Tianjin",
  "Chongqing",
  "Dalian",
  "Qingdao",
  "Xiamen",
  "Fuzhou",
  "Hefei",
  "Jinan",
  "Urumqi",
  "Lhasa",
  "Xi'an",
  "Guilin",
  "Suzhou",
  "Nanchang",
  "Hohhot",
  "Zhengzhou",
  "Yangon",
  "Surabaya",
  "Medan",
  "Bandung",
  "Makassar",
  "Batam",
  "Palembang",
  "Denpasar",
  "Semarang",
  "Manado",
  "Pekanbaru",
  "Balikpapan",
  "Pontianak",
  "Malang",
  "Tangerang",
  "Depok",
  "Bekasi",
  "Bandar Lampung",
  "Serang",
  "Mataram",
  "Kupang",
  "Douala",
  "Kigali",
  "Bujumbura",
  "Gaborone",
  "Windhoek",
  "Lusaka",
  "Lilongwe",
  "Maputo",
  "Antananarivo",
  "Nouakchott",
  "Dakar",
  "Banjul",
  "Freetown",
  "Monrovia",
  "Lome",
  "Cotonou",
  "Niamey",
  "Ouagadougou",
  "Bamako",
  "Ndjamena",
  "Bangui",
  "Kinshasa",
  "Brazzaville",
  "Libreville",
  "Malabo",
  "Victoria",
  "Moroni",
  "Sao Tome",
  "Djibouti",
  "Asmara",
  "Mogadishu",
  "Juba",
  "Dodoma",
  "Lusaka",
  "Harare",
  "Maputo",
  "Gitega",
  "Port Louis",
  "Mbabane",
  "Maseru",

  // Indian States
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chhattisgarh",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "Tripura",
  "Uttar Pradesh",
  "Uttarakhand",
  "West Bengal",

  // Major Local Areas in India
  "Connaught Place",
  "Bandra",
  "Salt Lake City",
  "T. Nagar",
  "Basavanagudi",
  "Charminar",
  "Shivajinagar",
  "Chandni Chowk",
  "Koramangala",
  "Viman Nagar",
  "Anna Nagar",
  "Powai",
  "Whitefield",
  "Park Street",
  "South Extension",
  "Karol Bagh",
  "Kothrud",
  "MG Road",
  "Rajajinagar",
  "Hauz Khas",
  "Sarojini Nagar",
  "Gariahat",
  "Marathahalli",
  "Indiranagar",
  "Ballygunge",
  "Electronic City",
  "Banashankari",
  "Thane West",
  "Goregaon East",
  "Behala",
];
